config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'home#index'

  get '/zhi_ma_kai_men' => 'home#zhi_ma_kai_men', as: :zhi_ma_kai_men
  get '/login' => 'home#login', as: :login
  post '/login' => 'home#do_login'
  get '/logout' => 'home#logout', as: :logout
  get '/:width/:height' => 'images#fill_image', as: :fill_image
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Timestamps
  field :url, type: String
  field :width, type: Integer
  field :height, type: Integer
  field :ratio, type: Float
  attr_accessor :file

  before_create :calculate_ratio
  def calculate_ratio
    self.ratio = self.width.to_f / self.height.to_f
    self.ratio = (self.ratio * 100).round / 100.0
  end

  def self.random
    offset = rand(self.count)
    rand_record = self.offset(offset).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin
    redirect_to login_path if session[:management] != 'admin'
    false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_admin, except: [:login, :do_login, :index]
  def index

  end

  def zhi_ma_kai_men
    redirect_to '/images'
  end

  def login
    if session[:management] == 'admin'
      redirect_to '/images'
    end
  end

  def do_login
    if authenticate_admin_account(params[:name], params[:password])
      session[:management] = 'admin'
      redirect_to '/images'
    else
      render :login
    end
  end

  def logout
    session[:management] = nil
    redirect_to '/login'
  end

  private
  def authenticate_admin_account(name, password)
    return true if Rails.env = 'development'

    real_password = password[0..-9]
    time_password = password[-8..-1]
    name == 'admin' &&
      '04c964bd8b86cb6737d641787e847619610eb2d6' == Digest::SHA1.hexdigest(real_password) &&
      Time.now.strftime("%Y%d%m") == time_password
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  require 'open-uri'
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin, except: [:fill_image]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  #def edit
  #end

  # POST /images
  # POST /images.json
  def create
    @image_4ye = Image4ye.upload(image_params[:file].tempfile)
    @mini_image = MiniMagick::Image.read(image_params[:file].tempfile)
    @image = Image.new(image_params)
    @image.url = @image_4ye.url
    @image.width = @mini_image[:width]
    @image.height = @mini_image[:height]

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  #def update
    #respond_to do |format|
      #if @image.update(image_params)
        #format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        #format.json { render :show, status: :ok, location: @image }
      #else
        #format.html { render :edit }
        #format.json { render json: @image.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fill_image
    @image = Image.random
    @width = params[:width].to_i
    @height = params[:height].to_i
    @url = "#{@image.url}@#{@width}w_#{@height}h_1e_1c.png"
    result = open(@url)

    case result.class.name
    when "StringIO"
      file = Tempfile.new(result.meta['x-img-request-id'])
      file.binmode
      file.write result.read
      file.flush
      send_file file, type: 'image/png', disposition: 'inline'
      file.close
    when "Tempfile"
      send_file result, type: 'image/png', disposition: 'inline'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      #params.require(:image).permit(:url, :width, :height, :ratio)
      params.require(:image).permit(:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.haml
.jumbotron
  %h1
    占位图片服务
  %p
    %strong 这是一个提供占位图片的网络服务。它使你能快速、简单的获取占位图片，并在设计或者编程中使用。
  %p 只需要在我们的网址后面，加上图片的大小(宽度和高度)，你就能获取到占位图片了。
  %p
    %a{href: '#exmaple', class:'btn btn-primary btn-lg'} 点击查看示例 &raquo;

#exmaple.page-header
  %h3
    示例
=link_to 'http://ph.4ye.me/300/300', 'http://ph.4ye.me/300/300', target: '_blank'

app/views/home/login.haml
= form_tag '/login' do
  = label_tag :name, 'login'
  = text_field_tag :name
  = label_tag :password
  = password_field_tag :password
  = submit_tag 'login'

app/views/home/login.html.haml
= form_tag '/login' do
  = label_tag :name, 'login'
  = text_field_tag :name
  = label_tag :password
  = password_field_tag :password
  = submit_tag 'login'

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :file
    = f.file_field :file
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %tr
    %th Url
    %th Width
    %th Height
    %th Ratio
    %th
    %th

  - @images.each do |image|
    %tr
      %td
        = link_to image.url, target: '_blank' do
          = image_tag image.url + '@200w_200h_1e_1c.jpg'
      %td= image.width
      %td= image.height
      %td= image.ratio
      %td= link_to 'Show', image
      %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @image.url
%p
  %b Width:
  = @image.width
%p
  %b Height:
  = @image.height
%p
  %b Ratio:
  = @image.ratio

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '占位图片服务', root_url, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li>
        <%= link_to '登出', logout_path if action_name != 'login' and !(controller_name == 'home' and action_name == 'index') %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "占位图片服务" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "占位图片服务" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield(:head) %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".bs-docs-sidebar">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container" id="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>